[ids]
*
# magic keyboard id
-004c:0267

# corne keyboard id
-55d4:0461

[main]
# swap caps lock and esc
capslock = overload(control, esc)
esc = capslock

# swap left meta and left alt
leftalt = leftmeta
leftmeta = leftalt
