$font = JetbrainsMonoNL Nerd Font

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    color = rgba(59, 66, 82, 1.0)
    blur_passes = 0
}

# white border box
shape {
    monitor =
    size = 30%, 20%
    color = rgba(0, 0, 0, 0.0)
    border_size = 1
    border_color = rgba(255, 255, 255, 1.0)
    position = 0, 0
    halign = center
    valign = center
}

# clock
label {
    monitor =
    text = $TIME 
    font_family = $font
    font_size = 100
    color = rgba(255, 255, 255, 1.0)
    position = 0, 15%
    halign = center
    valign = center
}

# session selector (fake ui element)
label {
    monitor =
    text = < Hyprland >
    font_family = $font
    font_size = 24
    color = rgba(255, 255, 255, 1.0)
    position = 0, 7%
    halign = center
    valign = center
}

# login label
label {
    monitor =
    text = login:
    font_family = $font
    font_size = 24
    color = rgba(255, 255, 255, 1.0)
    position = -50, -15
    halign = center
    valign = center
}

# username label
label {
    monitor =
    text = $USER
    font_family = $font
    font_size = 24
    color = rgba(255, 255, 255, 1.0)
    position = 40, -15 # Offset to align with "login:"
    halign = center
    valign = center
}

# password label
label {
    monitor =
    text = password:
    font_family = $font
    font_size = 24
    color = rgba(255, 255, 255, 1.0)
    position = -62, -50
    halign = center
    valign = center
}

# input field
input-field {
    monitor =
    size = 150, 30
    outline_thickness = 0
    dots_text_format = *
    dots_size = 0.8
    dots_spacing = 0.2
    dots_center = false
    dots_rounded = false 
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgb(255, 255, 255)
    font_family = $font
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 65, -50
    halign = center
    valign = center
    zindex = 10
}
