$font = JetBrainsMono Nerd Font
$colorlight = rgba(d8dee9dc)
$colordarker = rgba(216, 222, 233, .7) 
$failcolor = rgb(bf616a)

background {
  monitor =
  path = screenshot
  blur_passes = 3
}

general {
  no_fade_in = false
  grace = 0
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  fail_timeout = 1000
}

# clock
label {
  monitor =
  text = $TIME
  color = $colorlight
  font_size = 140
  font_family = $font Bold
  position = 0, 20%
  halign = center
  valign = center
}

# date
label {
  monitor =
  text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
  color = $colordarker
  font_size = 28
  font_family = $font
  position = 0, 12%
  halign = center
  valign = center
}


# username
label {
  monitor =
  text =   $USER
  color = $colorlight
  outline_thickness = 2
  font_size = 20
  font_family = $font
  position = 0, -6%
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 350, 70
  outline_thickness = 2
  dots_size = 0.3
  dots_spacing = 0.2
  dots_text_format = *
  dots_center = true
  outer_color = rgba(255, 255, 255, 0)
  inner_color = rgba(125,125,125, 0.2)
  font_color = rgb(225, 225, 225)
  fade_on_empty = false
  font_family = $font
  placeholder_text = password
  hide_input = false
  position = 0, -10%
  halign = center
  valign = center

  check_color = $failcolor
  fail_color = $failcolor
  fail_text = incorrect
}

# music
label {
  monitor =
  text = cmd[update:2000] /bin/sh -c 'artist=$(playerctl metadata artist 2>/dev/null); title=$(playerctl metadata title 2>/dev/null); if [[ -n "$artist" && -n "$title" ]]; then echo "󰫔 ${artist} - ${title}"; else echo ""; fi'
  font_size = 20
  font_family = $font
  color = $colordarker
  position = 0, -45%
  halign = center
  valign = center
}
