# nord theme
include ./nord.conf
dynamic_background_opacity yes
background_opacity 0.5

# general settings
enable_audio_bell no
sync_to_monitor no

# font
font_family JetBrainsMonoNL Nerd Font
font_size 11.5

