#------------------------------
# layouts
# ------------------------------
enabled_layouts splits,stack

# ------------------------------
# keybinds
# ------------------------------
# reload config
map ctrl+s>r combine : load_config_file : launch --type=overlay sh -c "echo 'Config reloaded!'; sleep 0.5"

# splitting
map ctrl+s>v launch --location=vsplit --cwd=current
map ctrl+s>o launch --location=hsplit --cwd=current

# zoom/fullscreen pane
map ctrl+s>f toggle_layout stack

# window navigation
map ctrl+s>c new_tab
map ctrl+s>n next_tab
map ctrl+s>p previous_tab
map ctrl+s>1 goto_tab 1
map ctrl+s>2 goto_tab 2
map ctrl+s>3 goto_tab 3
map ctrl+s>4 goto_tab 4

# pane navigation
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+l kitten pass_keys.py right  ctrl+l

# ------------------------------
# appearance
# ------------------------------
tab_bar_edge top
# tab_bar_min_tabs 1
tab_bar_align center
tab_bar_style separator
tab_bar_margin_height 5 0
tab_separator " "
tab_bar_margin_width 15

# tabs
active_tab_foreground   #2e3440
active_tab_background   #81a1c1
active_tab_font_style   bold
inactive_tab_foreground #d8dee9
inactive_tab_background #2e3440
inactive_tab_font_style normal

# tab title formatting
tab_title_template "{fmt.fg._3b4252}{fmt.bg.default}{fmt.fg._d8dee9}{fmt.bg._3b4252} {title[:20]} {fmt.fg._3b4252}{fmt.bg.default}"
active_tab_title_template "{fmt.fg._81a1c1}{fmt.bg.default}{fmt.fg._2e3440}{fmt.bg._81a1c1} {title[:20]}{layout_name == 'stack' and ' 󰁌 ZOOM' or ''} {fmt.fg._81a1c1}{fmt.bg.default}"

# pane borders
active_border_color #81a1c1
inactive_border_color #3b4252
window_border_width 1pt
inactive_text_alpha 0.8 
