##############################
# windowrules
##############################


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-drags
  match:class = ^$ match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = true
}


# wiremix
windowrule = match:class ^(wiremix-tui)$, float 1
windowrule = match:class ^(wiremix-tui)$, center 1
windowrule = match:class ^(wiremix-tui)$, size 800 400

# general apps
windowrule = match:class spotify, workspace special:magic
layerrule = match:class selector, no_anim on
windowrule = match:class Sxiv, float 1, center 1, size 1000 600
windowrule = match:class com.soton.sddp.App, float 1
windowrule = match:class ^zen$, match:title ^(Extension), float 1
windowrule = match:class Tk, float 1, center 1
windowrule = match:class thunar, match:title Rename.*, float 1

# Java / SceneBuilder flickering fixes
windowrule = match:class ^SceneBuilder$, match:title ^SceneBuilder$, no_focus on
windowrule = match:class ^SceneBuilder$, match:title ^SceneBuilder$, no_initial_focus on
windowrule = match:class ^SceneBuilder$, match:title ^SceneBuilder$, border_size 0
windowrule = match:class ^SceneBuilder$, match:title ^SceneBuilder$, no_shadow on
windowrule = match:class ^(com\.oracle\.javafx\.scenebuilder\.app\.SceneBuilderApp)$, match:float 1, no_initial_focus on
windowrule = match:class ^(com\.oracle\.javafx\.scenebuilder\.app\.SceneBuilderApp)$, match:float 0, stay_focused 1

